# Generated by Django 5.0.7 on 2024-08-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_feedback_score_alter_feedback_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
