# Generated by Django 5.0.7 on 2024-08-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(0, "Personal"), (1, "Team"), (2, "All")], default=2),
        ),
    ]
