# Generated by Django 5.0.7 on 2024-08-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
        ("user", "0003_alter_team_invite_alter_user_invite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=True, help_text="When set to false, the notification is hidden fr"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="end",
            field=models.DateTimeField(
                blank=True, help_text="If set, notification is hidden after this time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="start",
            field=models.DateTimeField(
                blank=True, help_text="If set, notification is hidden before this time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Notification recipient",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="user.team",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Personal"), (1, "Team"), (2, "All")], default=2, help_text="Who can see the notification"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Notification recipient",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
