# Generated by Django 5.0.7 on 2024-08-03 17:38

import uuid

from django.db import migrations, models

import backend.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="invite",
            field=models.CharField(default=uuid.uuid4, help_text="Invite code to join team", max_length=36),
        ),
        migrations.AlterField(
            model_name="user",
            name="invite",
            field=models.CharField(default=uuid.uuid4, help_text="Invite code to link account", max_length=36),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=backend.user.models.get_password, max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="student",
            field=models.BooleanField(default=True, help_text="Whether or not the user is a student"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Username, by default 'Last name First name'", max_length=150, unique=True
            ),
        ),
    ]
