# Generated by Django 5.0.7 on 2024-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_challenge_regexp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="correct",
            field=models.BooleanField(default=True),
        ),
    ]
