# Generated by Django 5.0.7 on 2024-08-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0004_alter_submission_correct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="dynamic",
        ),
        migrations.AddField(
            model_name="challenge",
            name="review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="challenge.challenge"
            ),
        ),
    ]
