# Generated by Django 5.0.7 on 2024-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0005_remove_challenge_dynamic_challenge_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="active",
            field=models.BooleanField(default=True, help_text="When set to false, the challenge is hidden"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="end",
            field=models.DateTimeField(blank=True, help_text="If set, challenge is hidden after this time", null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="When set to true, the challenge is not visible, but it can still be submitted"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="regexp",
            field=models.BooleanField(default=False, help_text="Whether or not the flag is a regular expression"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="review",
            field=models.BooleanField(
                default=False, help_text="Whether or not the challenge requires review from the admins team"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start",
            field=models.DateTimeField(blank=True, help_text="If set, challenge is hidden before this time", null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="team",
            field=models.BooleanField(default=False, help_text="Whether or not the challenge is a team challenge"),
        ),
    ]
